export const CREATE_NOTE_CATEGORY_REQUEST = "CREATE_NOTE_CATEGORY_REQUEST";
export const CREATE_NOTE_CATEGORY_SUCCESS = "CREATE_NOTE_CATEGORY_SUCCESS";
export const CREATE_NOTE_CATEGORY_FAILURE = "CREATE_NOTE_CATEGORY_FAILURE";

export const CREATE_NOTE_REQUEST = "CREATE_NOTE_REQUEST";
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
export const CREATE_NOTE_FAILURE = "CREATE_NOTE_FAILURE";

export const FETCH_NOTES_REQUEST = "FETCH_NOTES_REQUEST";
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";
export const FETCH_NOTES_FAILURE = "FETCH_NOTES_FAILURE";

export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";

export const FETCH_INVOICE_NUMBER_REQUEST = 'FETCH_INVOICE_NUMBER_REQUEST';
export const FETCH_INVOICE_NUMBER_SUCCESS = 'FETCH_INVOICE_NUMBER_SUCCESS';
export const FETCH_INVOICE_NUMBER_FAILURE = 'FETCH_INVOICE_NUMBER_FAILURE';

export const createNoteCategory = (name) => ({
  type: CREATE_NOTE_CATEGORY_REQUEST,
  payload: { name },
});

export const createNote = (note) => ({
  type: CREATE_NOTE_REQUEST,
  payload: note,
});

export const fetchNotes = () => ({
  type: FETCH_NOTES_REQUEST,
});

export const fetchCategories = () => ({
  type: FETCH_CATEGORIES_REQUEST,
});
  
