export const REQUEST_USER_EXCEL = "REQUEST_USER_EXCEL";
export const REQUEST_ADMIN_EXCEL = "REQUEST_ADMIN_EXCEL";
export const ERROR_EXCEL = "ERROR_EXCEL";
export const SET_EXCEL_RESPONSE = "SET_EXCEL_RESPONSE";