export const GET_DAILY_REPORTS_REQUEST = "GET_DAILY_REPORTS_REQUEST";
export const GET_DAILY_REPORTS_SUCCESS = "GET_DAILY_REPORTS_SUCCESS";
export const GET_DAILY_REPORTS_FAILURE = "GET_DAILY_REPORTS_FAILURE";

export const GET_MONTHLY_REPORTS_REQUEST = "GET_MONTHLY_REPORTS_REQUEST";
export const GET_MONTHLY_REPORTS_SUCCESS = "GET_MONTHLY_REPORTS_SUCCESS";
export const GET_MONTHLY_REPORTS_FAILURE = "GET_MONTHLY_REPORTS_FAILURE";

export const GET_YEARLY_REPORTS_REQUEST = "GET_YEARLY_REPORTS_REQUEST";
export const GET_YEARLY_REPORTS_SUCCESS = "GET_YEARLY_REPORTS_SUCCESS";
export const GET_YEARLY_REPORTS_FAILURE = "GET_YEARLY_REPORTS_FAILURE";
