export const REQUEST_TODAY_PRODUCT = "REQUEST_TODAY_PRODUCT";
export const FETCH_TODAY_PRODUCT="FETCH_TODAY_PRODUCT"

export  const REQUEST_CUSTOME_PRODUCT = "REQUEST_CUSTOME_PRODUCT"
export const FETCH_CUSTOME_PRODUCT = "FETCH_CUSTOME_PRODUCT"

export  const REQUEST_MONTHLY_PRODUCT = "REQUEST_MONTHLY_PRODUCT"
export const FETCH_MONTHLY_PRODUCT = "FETCH_MONTHLY_PRODUCT"

export  const REQUEST_QUARTERLY_PRODUCT = "REQUEST_QUARTERLY_PRODUCT"
export const FETCH_QUARTERLY_PRODUCT = "FETCH_QUARTERLY_PRODUCT"

export  const REQUEST_YEARLY_PRODUCT = "REQUEST_YEARLY_PRODUCT"
export const FETCH_YEARLY_PRODUCT = "FETCH_YEARLY_PRODUCT"

export const FILTER_DAILY = "FILTER_DAILY"
export const FILTER_MONTHLY = "FILTER_MONTHLY"
export const FILTER_YEARLY = "FILTER_YEARLY"
