export const REQUEST_CREATE_INVOICE = "REQUEST_CREATE_INVOICE";
export const SET_CREATE_INVOICE = "SET_CREATE_INVOICE";
export const ERROR_CREATE_INVOICE = "ERROR_CREATE_INVOICE";

export const REQUEST_INVOICE_DATA = "REQUEST_INVOICE_DATA";
export const SET_INVOICE_DATA = "SET_INVOICE_DATA";

export const REQUEST_EDIT_INVOICE_DATA = "REQUEST_EDIT_INVOICE_DATA";
export const SET_EDIT_INVOICE_DATA = "SET_EDIT_INVOICE_DATA";
