export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const REQUEST_CATEGORY = "REQUEST_CATEGORY";
export const SET_CATEGORY = "SET_CATEGORY";
export const ERROR_CATEGORY = "ERROR_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const REQUEST_UPDATE_CATEGORY = "REQUEST_UPDATE_CATEGORY";

