export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const PRODUCT_REQUEST = "PRODUCT_REQUEST"
export const REQUEST_UPDATE_PRODUCT = "REQUEST_UPDATE_PRODUCT";
export const REQUEST_STOCK_QUANTITY = "REQUEST_STOCK_QUANTITY";
export const SET_PRODUCT = "SET_PRODUCT"
export const ERROR_PRODUCT = "ERROR_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT";

