export const CREATE_SUBCATEGORY_REQUEST = "CREATE_SUBCATEGORY_REQUEST";
export const REQUEST_SUBCATEGORY = "REQUEST_SUBCATEGORY";
export const REQUEST_UPDATE_SUBCATEGORY = "REQUEST_UPDATE_SUBCATEGORY";
export const RECEIVE_SUBCATEGORY = "RECEIVE_SUBCATEGORY";
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY";
export const ERROR_SUBCATEGORY = "ERROR_SUBCATEGORY";

