export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_UPDATEDCART = "ADD_TO_UPDATEDCART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const CLEAR_PURCHASE_CART = "CLEAR_PURCHASE_CART";

export const EDIT_PURCHASE_DATA = "EDIT_PURCHASE_DATA";
export const ADD_TO_PURCHASE_CART = "ADD_TO_PURCHASE_CART";
export const REMOVE_FROM_PURCHASE_CART = "REMOVE_FROM_PURCHASE_CART";
