export const REQUEST_BILL_NO = "REQUEST_BILL_NO";
export const REQUEST_BILL = "REQUEST_BILL";
export const RETURN_BILL_NO ="RETURN_BILL_NO";
export const REQUEST_BHET_BILL_NO = "REQUEST_BHET_BILL_NO";

export const SET_BILL_NO = "SET_BILL_NO";
export const ERROR_BILL_NO = "ERROR_BILL_NO";

export const REPRINT_BILL = "REPRINT_BILL";
export const SET_REPRINT_BILL = "SET_REPRINT_BILL"; 
export const ERROR_REPRINT_BILL = "ERROR_REPRINT_BILL"; 

export const REQUEST_BILL_DETAILS = "REQUEST_BILL_DETAILS";
export const SET_BILL_DETAILS = "SET_BILL_DETAILS";
export const ERROR_BILL_DETAILS = "ERROR_BILL_DETAILS";

export const REQUEST_CREATE_BILL = "REQUEST_CREATE_BILL";
export const SET_CREATE_BILL = "SET_CREATE_BILL";
export const ERROR_CREATE_BILL = "ERROR_CREATE_BILL";

export const REQUEST_RETURN_BILL = "REQUEST_RETURN_BILL";
export const SET_RETURN_BILL = "SET_RETURN_BILL";
export const ERROR_RETURN_BILL = "ERROR_RETURN_BILL";

